export const defaultPricingItems = [
  {
    category: "PIN",
    name: "Kiểm tra tình trạng pin",
    price: "Miễn phí",
    unit: "VNĐ",
    description: null,
    note: "Quyền lợi trước khi chốt sửa hoặc đóng lại",
    sortOrder: 10,
    active: true,
  },
  {
    category: "PIN",
    name: "Pin máy khoan / bắn vít",
    price: "350.000 - 800.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ dung lượng & hãng",
    sortOrder: 20,
    active: true,
  },
  {
    category: "PIN",
    name: "Pin máy cắt / máy mài",
    price: "500.000 - 1.200.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ số cell",
    sortOrder: 30,
    active: true,
  },
  {
    category: "PIN",
    name: "Pin xe đạp điện",
    price: "2.000.000 - 5.000.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ Ah & loại xe",
    sortOrder: 40,
    active: true,
  },
  {
    category: "PIN",
    name: "Pin xe máy điện",
    price: "3.500.000 - 8.000.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ dung lượng",
    sortOrder: 50,
    active: true,
  },
  {
    category: "PIN",
    name: "Pin loa kéo",
    price: "200.000 - 500.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ hãng loa",
    sortOrder: 60,
    active: true,
  },
  {
    category: "NLMT",
    name: "Thay pin đèn NLMT",
    price: "150.000 - 400.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ dung lượng",
    sortOrder: 10,
    active: true,
  },
  {
    category: "NLMT",
    name: "Đèn pha NLMT 100W-300W",
    price: "500.000 - 1.500.000",
    unit: "VNĐ",
    description: null,
    note: "Bao lắp đặt",
    sortOrder: 20,
    active: true,
  },
  {
    category: "LUU_TRU",
    name: "Pin kích đề ô tô 12V",
    price: "800.000 - 2.000.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ dòng xả",
    sortOrder: 10,
    active: true,
  },
  {
    category: "LUU_TRU",
    name: "Pin dự phòng dung lượng lớn",
    price: "500.000 - 3.000.000",
    unit: "VNĐ",
    description: null,
    note: "Tuỳ mAh",
    sortOrder: 20,
    active: true,
  },
  {
    category: "LUU_TRU",
    name: "Đóng bình pin theo yêu cầu",
    price: "Liên hệ",
    unit: "VNĐ",
    description: null,
    note: "Báo giá theo thông số",
    sortOrder: 30,
    active: true,
  },
  {
    category: "CAMERA",
    name: "Trọn bộ 2 camera",
    price: "2.500.000 - 4.000.000",
    unit: "VNĐ",
    description: null,
    note: "Bao lắp đặt",
    sortOrder: 10,
    active: true,
  },
  {
    category: "CAMERA",
    name: "Trọn bộ 4 camera",
    price: "4.000.000 - 7.000.000",
    unit: "VNĐ",
    description: null,
    note: "Bao lắp đặt",
    sortOrder: 20,
    active: true,
  },
  {
    category: "CAMERA",
    name: "Camera PTZ xoay 360°",
    price: "1.500.000 - 3.000.000",
    unit: "VNĐ/cam",
    description: null,
    note: "Tuỳ hãng",
    sortOrder: 30,
    active: true,
  },
  {
    category: "CAMERA",
    name: "Khảo sát tận nơi",
    price: "Miễn phí",
    unit: "VNĐ",
    description: null,
    note: "Đà Nẵng & lân cận",
    sortOrder: 40,
    active: true,
  },
] as const;

export function getDefaultPricingByCategory(category: string) {
  return defaultPricingItems.filter((item) => item.category === category);
}
